[package]
name = 'printer'
version = '0.1.0'
authors = ['Bruno Tavares <connect+github@bltavares.com>']
edition = '2018'

[dependencies]
env_logger = '=0.7.1'
log = '=0.4.11'

[dependencies.async-std]
version = '=1.6.0'
features = ['unstable']
